services:
  jitsi-web-overlay-backend:
    build:
      context: ./jitsi-web-overlay-backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - '${BACKEND_PORT}:3030'
    restart: always
    depends_on:
      - mariadb
    volumes:
      - visioreplay_data:/data/visioreplay

  jitsi-web-overlay-frontend:
    build:
      context: ./jitsi-web-overlay-frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${API_URL}
        VITE_APP_TEMPLATE: ${APP_TEMPLATE}
    ports:
      - '${FRONTEND_PORT}:80'
    restart: always
    depends_on:
      - jitsi-web-overlay-backend
    volumes:
    - ./client-resources:/usr/share/nginx/html/assets/client-resources:ro


  mariadb:
    image: mariadb:11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql

  visioreplay-ssh-v3:
    image: alpine:latest
    env_file: ./.env
    restart: always
    ports:
      - ${HOST_DATA_SSH_PORT}:22
    command:
      - /bin/sh
      - -c
      - addgroup --gid 101 -S jibri-k8s-record;
        adduser --uid 1000 jibri-k8s-record -G jibri-k8s-record;
        chown -R jibri-k8s-record:jibri-k8s-record /data/visioreplay;
        echo 'jibri-k8s-record:SuperlonguCledeplusde50charDeLutilisateurquinutiliserajamaissonmotdepasse' | chpasswd;
        apk add rsync;
        apk add --no-cache openssh;
        echo 'PasswordAuthentication no' >> /etc/ssh/sshd_config;
        echo 'PermitRootLogin no' >> /etc/ssh/sshd_config;
        ssh-keygen -A;
        /usr/sbin/sshd -D -d -p 22;
    volumes:
      - ./jibri-k8s-record_home:/home/jibri-k8s-record
      - visioreplay_data:/data/visioreplay

volumes:
  visioreplay_data:
  mariadb_data:
