services:
  jitsi-web-overlay-backend:
    build:
      context: ./jitsi-web-overlay-backend
      dockerfile: Dockerfile.dev
    ports:
      - "3030:3030"
    volumes:
      - ./jitsi-web-overlay-backend:/app
      - node_modules_backend:/app/node_modules
    env_file:
      - .env.development
    depends_on:
      - mariadb

    command: npx nodemon src/main.ts

  jitsi-web-overlay-frontend:
    build:
      context: ./jitsi-web-overlay-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    volumes:
      - ./jitsi-web-overlay-frontend:/app
      - node_modules_frontend:/app/node_modules
    command: npm run dev -- --host

  mariadb:
    image: mariadb:11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
  mongo_data:
  node_modules_backend:
  node_modules_frontend:
