

FROM node:bookworm


WORKDIR /app

COPY package*.json ./


COPY . .



RUN npm install --force
RUN cp -r node_modules/@apitechfr/react-dsapitech/dsfr public/dsfr/ 2>/dev/null || true



EXPOSE 3000


CMD ["npm", "run", "dev"]