services:
  plugin-outlook-joona:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PLUGIN_PORT}:80"

    environment:
      NODE_ENV: production
    restart: always
