services:
  plugin-outlook-joona:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PLUGIN_PORT}:80"

    environment:
      NODE_ENV: production
      ROOM_NAME_LENGTH: ${ROOM_NAME_LENGTH}
      ROOM_NAME_PREFIX: ${ROOM_NAME_PREFIX}
      ROOM_NAME_MODE: ${ROOM_NAME_MODE}
      DIALINNUMBER_URL: ${DIALINNUMBER_URL}
      DIALINCONFCODE_URL: ${DIALINCONFCODE_URL}
      ENABLE_PHONE_ACCESS: ${ENABLE_PHONE_ACCESS}
      JITSI_DOMAIN: ${JITSI_DOMAIN}
      PHONE_NUMBER_FORMAT: ${PHONE_NUMBER_FORMAT}
      ENABLE_MODERATOR_OPTIONS: ${ENABLE_MODERATOR_OPTIONS}
      TITLE_MEETING_DETAILS: ${TITLE_MEETING_DETAILS}
      DEBUG: ${DEBUG}
    restart: always
